# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/process_reads.smk"
include: "rules/reports.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        # expand("results/bwa_mem/{sample}.bam", sample=dnaseq.index.unique()),
        # expand("results/vireo/{id}", id=scrnaseq.index.unique()),
        "reports/report_vireo_all.html",
        # "Rlib_DropletQC",
        expand("reports/report_dropletqc_vireo/{id}.html", id=scrnaseq.index.unique()),
        "results/mrna_bed/mRNAs.bed",
        "results/multiqc/qc/multiqc.html",
    default_target: True
