$schema: "http://json-schema.org/draft-07/schema#"
description: main configuration schema for the workflow
properties:
  dnaseq_samplesheet:
    type: string
    description: path to sample-sheet TSV file

  genome:
    type: object
    properties:
      fasta:
        type: string
        description: path to fasta file (and index files) of the reference genome
    required: ["fasta"]

required:
  - dnaseq_samplesheet
  - genome
