---
title: "Vireo (combined report)"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
library(DropletUtils)
library(kableExtra)
library(tidyverse)
```

```{r snakemake}
vireo_result_dirs <- snakemake@input[["vireo"]]
cellranger_result_dirs <- snakemake@input[["cellranger"]]
```

```{r vireo_summary_files}
vireo_summary_files <- file.path(vireo_result_dirs, "summary.tsv")
```

```{r cellranger_h5_files}
cellranger_h5_files <- file.path(cellranger_result_dirs, "outs", "filtered_feature_bc_matrix.h5")
```

## Load data

```{r debug, echo=FALSE}
load_one_file <- function(path) {
  res <- read_tsv(path, show_col_types = FALSE)
  colnames(res) <- c("label", "frequency")
  res$sample <- basename(dirname(path))
  res
}
vireo_summary_all <- do.call("bind_rows", lapply(vireo_summary_files, load_one_file)) %>%
  mutate(sample = str_replace(sample, "WPP000_018hrs_", ""))
vireo_summary_all %>%
  select(sample, label, frequency)
```

<!-- Remove doublets and unassigned -->

```{r vireo_summary_all_assigned, echo=FALSE}
vireo_summary_all_assigned <- vireo_summary_all %>%
  filter(!label %in% c("doublet", "unassigned"))
```

<!-- Order assigned labels by total frequency -->

```{r labels_ordered_by_assigned_cells, echo=FALSE}
labels_ordered_by_assigned_cells <- vireo_summary_all_assigned %>%
  group_by(label) %>%
  summarise(frequency = sum(frequency)) %>%
  arrange(desc(frequency)) %>%
  pull(label)
vireo_summary_all_assigned <- vireo_summary_all_assigned %>%
  mutate(label = factor(label, labels_ordered_by_assigned_cells))
```

## Cell assignments compared across samples

```{r ggplot_label_frequency_sample, echo=FALSE}
ggplot(vireo_summary_all_assigned, aes(x = label, y = frequency, colour = sample)) +
  geom_point() +
  geom_line(aes(group = sample)) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(
    x = "Sample",
    y = "Frequency",
    title = "Cell assignments compared across samples"
  ) +
  theme_bw()
```

```{r table_label_frequency_sample, echo=FALSE}
vireo_summary_all_assigned %>% 
  pivot_wider(names_from = sample, values_from = frequency) %>% 
  arrange(label) %>%
  knitr::kable(format.args = list(big.mark = ","))
```

## Total cell assigned per sample

```{r vireo_summary_all_assigned_total, echo=FALSE}
vireo_summary_all_assigned_total <- vireo_summary_all_assigned %>%
  select(-label) %>%
  group_by(sample) %>%
  summarise(
    frequency = sum(frequency)
  )
```

```{r ggplot_total_frequency_sample, echo=FALSE}
ggplot(vireo_summary_all_assigned_total, aes(x = sample, y = frequency, fill = sample)) +
  geom_col(alpha = 0.5) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(
    x = "Sample",
    y = "Frequency",
    title = "Total assignments per sample"
  ) +
  theme_bw()
```

```{r print_vireo_summary_all_assigned_total, echo=FALSE}
vireo_summary_all_assigned_total %>%
  knitr::kable(format.args = list(big.mark = ",")) %>% 
  kableExtra::kable_styling(full_width = FALSE)
```

## Expression of sex genes by donor

Quality control: Within each demultiplexed sample, all cells should be male or female.

```{r sce, echo=FALSE}
names(cellranger_h5_files) <- str_replace(basename(dirname(dirname(cellranger_h5_files))), ".+_", "")
sce <- read10xCounts(samples = cellranger_h5_files)
colnames(sce) <- paste0(sce$Barcode, "-", sce$Sample)
# sce
```

```{r donor_ids, echo=FALSE}
vireo_donor_files <- file.path(vireo_result_dirs, "donor_ids.tsv")
load_one_donor_file <- function(path) {
  res <- read_tsv(path, show_col_types = FALSE)
  res$sample <- basename(dirname(path))
  res
}
vireo_donor_all <- do.call("bind_rows", lapply(vireo_donor_files, load_one_donor_file)) %>%
  mutate(sample = str_replace(sample, "WPP000_018hrs_", "")) %>% 
  mutate(barcode = paste0(cell, "-", sample))
stopifnot(all(vireo_donor_all$barcode %in% colnames(sce)))
stopifnot(all(colnames(sce) %in% vireo_donor_all$barcode))
stopifnot(!any(duplicated(colnames(sce))))
stopifnot(!any(duplicated(vireo_donor_all$barcode)))
# vireo_donor_all
```

```{r coldata_donor_id, echo=FALSE}
colData(sce)[vireo_donor_all$barcode, "donor_id"] <- vireo_donor_all$donor_id
```

```{r plot_rox2_by_donor, fig.height=6, fig.width=9, echo=FALSE, warning=FALSE}
gene_id <- "FBgn0019660"
gene_name <- rowData(sce)[gene_id, "Symbol"]
plot_data <- tibble(
  counts = counts(sce)[gene_id,],
  donor_id = colData(sce)[["donor_id"]]
)
ggplot() +
  geom_violin(aes(x = donor_id, y = counts, fill = donor_id), data = plot_data, scale = "width") +
  scale_y_log10() +
  labs(
    title = sprintf("%s | %s", gene_id, gene_name),
    subtitle = "UMI counts"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

## Session info

`r date()`

```{r session_info, echo=FALSE}
sessionInfo()
```
