---
title: "Droplet filtering metrics (sample)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(tidyverse)
```

```{r setup, include=FALSE}
# use this code chunk to set up constants
```

```{r snakemake, include=FALSE}
vireo_dir <- snakemake@input[["vireo"]]
dropletqc_csv <- snakemake@input[["dropletqc"]]
cellranger_tsv <- snakemake@input[["cellranger"]]
```

```{r vireo_file, include=FALSE}
vireo_file <- file.path(vireo_dir, "donor_ids.tsv")
```

## Information

```{r information, include=FALSE}
sample_name <- basename(vireo_dir)
```

- **Sample:** `r sample_name`
- **CellRanger file:** `r cellranger_tsv`
- **Vireo file:** `r vireo_file`
- **DropletQC file:** `r dropletqc_csv`

```{r sce, include=FALSE}
cellranger_data <- read_tsv(cellranger_tsv)
```

```{r cell_names, include=FALSE}
cell_names <- colnames(sce)
```

```{r vireo_data, include=FALSE}
# "results/vireo/{id}/summary.tsv" (character vector)
vireo_data <- read_tsv(vireo_file)
```

```{r dropletqc_data, include=FALSE}
dropletqc_data <- read_csv(dropletqc_csv, col_names = c("barcode", "nuclear_fraction"), skip = 1)
```

```{r cell_stats, include=FALSE}
cell_stats <- cellranger_data %>%
  left_join(
    dropletqc_data,
    by = c("barcode" = "cell")
  ) %>%
  left_join(
    vireo_data,
    by = "barcode"
  )
```

## Plots

### DropletQC-Vireo

```{r plot_assigned, echo=FALSE}
plot <- ggplot() +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(donor_id %in% c("doublet", "unassigned")),
    colour = "#b3b3b3",
    size = 0.1
  ) +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(!donor_id %in% c("doublet", "unassigned")),
    colour = "#F8766D",
    size = 0.1
  ) +
  labs(
    x = "Nuclear fraction",
    y = "UMI sum (log10)",
    title = sprintf("Assigned to donor (%s)", sample_name),
    subtitle = sprintf("%s barcodes", format(sum(!cell_stats$donor_id %in% c("doublet", "unassigned")), big.mark = ","))
  ) +
  guides(colour = "none") +
  theme_bw()
rasterise(plot, layers = "Point", dpi = 300)
```

```{r plot_doublet, echo=FALSE}
plot <- ggplot() +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(donor_id != "doublet"),
    colour = "#b3b3b3",
    size = 0.1
  ) +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(donor_id == "doublet"),
    colour = "#F8766D",
    size = 0.1
  ) +
  labs(
    x = "Nuclear fraction",
    y = "UMI sum (log10)",
    title = sprintf("Doublet (%s)", sample_name),
    subtitle = sprintf("%s barcodes", format(sum(cell_stats$donor_id == "doublet"), big.mark = ","))
  ) +
  guides(colour = "none") +
  theme_bw()
rasterise(plot, layers = "Point", dpi = 300)
```

```{r plot_unassigned, echo=FALSE}
plot <- ggplot() +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(donor_id != "unassigned"),
    colour = "#b3b3b3",
    size = 0.1
  ) +
  geom_point(
    mapping = aes(x = nuclear_fraction, y = log10(sum)),
    data = cell_stats %>% filter(donor_id == "unassigned"),
    colour = "#F8766D",
    size = 0.1
  ) +
  labs(
    x = "Nuclear fraction",
    y = "UMI sum (log10)",
    title = sprintf("Unassigned (%s)", sample_name),
    subtitle = sprintf("%s barcodes", format(sum(cell_stats$donor_id == "unassigned"), big.mark = ","))
  ) +
  guides(colour = "none") +
  theme_bw()
rasterise(plot, layers = "Point", dpi = 300)
```
