dnaseq_samplesheet: "config/dnaseq.tsv"

genome:
  index: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/genome/genome.fa"

bwa_mem:
  mem: 16G
  runtime: 1h

samtools_sort:
  mem: 16G
  runtime: 30m
