dnaseq_samplesheet: "config/dnaseq.tsv"
scrnaseq_samplesheet: "config/scrnaseq.tsv"

genome:
  fasta: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/genome/genome.fa"
  gtf: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/genome/genome.gtf"
  cellranger: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/cellranger_mkref"

bwa_mem:
  mem: 16G
  runtime: 1h

samtools_sort:
  mem: 16G
  runtime: 30m

mark_duplicates:
  mem: 8GG
  runtime: 1h

haplotype_caller:
  mem: 16G
  runtime: 4h

bcftools_view:
  mem: 12G
  runtime: 10m

cellranger_count:
  cpus: 20
  mem_gb: 40
  runtime: 12h

cellsnp_lite:
  cpus: 16
  mem: 16G
  runtime: 23h

# popscle_dsc:
#   mem: 128G
#   runtime: 6h

# popscle_demuxlet:
#   mem: 48G
#   runtime: 6h