dnaseq_samplesheet: "config/dnaseq.tsv"

genome:
  fasta: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/genome/genome.fa"
  gtf: "/ceph/project/cncb/albrecht/snakemake-cncb-index-ensembl-genome/results/genome/genome.gtf"

bwa_mem:
  mem: 16G
  runtime: 1h

samtools_sort:
  mem: 16G
  runtime: 30m

mark_duplicates:
  mem: 8GG
  runtime: 1h

haplotype_caller:
  mem: 16G
  runtime: 4h

bcftools_view:
  mem: 12G
  runtime: 10m
